#!/usr/bin/env bash
source ~/.config/bspwm/.bspwm

case "$THEME" in
iLight)
	dunst -config ~/.config/dunst/dunstrc-right &
	~/.config/bspwm/wallpaper/cw -set light.jpg
	xrdb -merge ~/.config/bspwm/ilight/.Xresources
	timeout 0.1s xsettingsd -c ~/.config/bspwm/ilight/.xsettingsd
	$NOTIFIER -r 13 -i "$ICONDIR/theme.png" -t 3500 -u low "Light Mode" "Change Theme" ;;
iDark)
	dunst -config ~/.config/dunst/dunstrc-dark-right &
	~/.config/bspwm/wallpaper/cw -set dark.png
	xrdb -merge ~/.config/bspwm/idark/.Xresources
	timeout 0.1s xsettingsd -c ~/.config/bspwm/idark/.xsettingsd
	$NOTIFIER -r 13 -i "$ICONDIR/theme.png" -t 3500 -u low "Dark Mode" "Change Theme" ;;
esac



